---
name: Test Build

on:
  pull_request:
    branches: [develop, main]
#  push:
#    branches:
#      - '*'
#    branches: [ develop, 0006__* ]  # Your feature branches

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      # Just test the build, don't create full installers
      - name: Test build
        run: mvn clean test
