name: sudoku
base: core22
version: '1.0.0'
summary: Sudoku game and editor
description: |
  A Sudoku application with both a console UI and a JavaFX GUI,
  featuring a game mode and a puzzle editor.

grade: stable        # use 'devel' during development
confinement: classic # JavaFX needs direct GPU/display access

architectures:
  - build-on: amd64

apps:
  sudoku:
    command: bin/launcher
    environment:
      JAVA_HOME: $SNAP/jre
      PATH: $SNAP/jre/bin:$PATH

# For all the sources the file take as base directory `target/snap_build`
# See the file `utils/build_snap.sh` to see how the base directory is prepared

parts:
  jre:
    plugin: dump
    source: jre/
    organize:
      '*': jre/

  app:
    plugin: dump
    source: jar/
    stage-packages: []
    organize:
      sudoku-1.0-SNAPSHOT.jar: app/sudoku.jar
    stage:
      - app/sudoku.jar

  modular-libs:
    plugin: dump
    source: lib/modular
    organize:
      '*': app/lib/

  classpath-libs:
    plugin: dump
    source: lib/classpath
    organize:
      '*': app/classpath/

  launcher:
    plugin: dump
    source: snap/local/
    organize:
      launcher: bin/launcher